version: '3.3'


services:

  db:
    image: postgres:13.10-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: leontiev93/infra_action:latest
    restart: always

    # build: 
    #   context: ./backend/
    #   dockerfile: Dockerfile
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      # - .env
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  frontend:
    depends_on:
      - backend
    image: leontiev93/infra_web:latest
    # build: 
    #   context: ./frontend/
    #   dockerfile: Dockerfile
    # env_file: .env
    # command: cp -r /app/dist/. /static/
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_static:/var/html/static/
      - backend_media:/var/html/media/
      - ../frontend/build:/usr/share/nginx/html/
#    command: "sudo docker cp -r photo_market_nginx_1:usr/share/nginx/html/static/* var/html/static"
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend

  # nginx:
  #   build: 
  #     context: ./infra
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: always
  #   volumes:
  #     - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - static:/app/static/
  #     # - static:/usr/share/nginx/html/
  #     - backend_static:/backend_static/
  #     - backend_media:/backend_media/

    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

volumes:
  static:
  backend_static:
  backend_media:
  pg_data:
