version: '3.5'

volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

services:

  db:
    image: postgres:13.10-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    env_file:
      - .env
    image: dpavlen/hakaton_backend
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/
    depends_on:
      - db

  frontend:
    image: dpavlen/hakaton_frontend
    command: cp -r /app/dist/. /static/
    volumes:
      - static:/static/

  nginx:
    restart: always
    image: dpavlen/hakaton_infra
    ports:
      - 8600:80
    volumes:
      # - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static/
      - backend_static:/backend_static/
      - backend_media:/backend_media/
    depends_on:
      - backend