version: '3.5'

volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

services:

  db:
    image: postgres:14.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    env_file: .env
    command: cp -r /app/dist/. /static/
    volumes:
      - static:/static/

  nginx:
    build:
      context: ./infra
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static/
      # - static:/usr/share/nginx/html/
      - backend_static:/backend_static/
      - backend_media:/backend_media/
