# Generated by Django 5.0.2 on 2024-03-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, verbose_name="название категории"),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="описание категории"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default=None,
                        upload_to="category/images/",
                        verbose_name="Фото категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TariffList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="название тарифа"),
                ),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="описание тарифа"),
                ),
                (
                    "services_duration",
                    models.CharField(
                        choices=[
                            ("one_month", "Один месяц"),
                            ("three_months", "Три месяца"),
                            ("six_months", "Шесть месяцев"),
                            ("one_year", "Один год"),
                        ],
                        default="one_month",
                        max_length=20,
                        verbose_name="длительность тарифа",
                    ),
                ),
                (
                    "tariff_full_price",
                    models.FloatField(verbose_name="полная стоимость тарифа"),
                ),
                (
                    "tariff_promo_price",
                    models.FloatField(verbose_name="промо стоимость тарифа"),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="название")),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=400, null=True, verbose_name="ссылка"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="описание"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default=None,
                        upload_to="services/images/",
                        verbose_name="Фото сервиса",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сервис",
                "verbose_name_plural": "Сервисы",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("subscribed", "Подписан"),
                            ("not_subscribed", "Не подписан"),
                        ],
                        default="subscribed",
                        max_length=20,
                        verbose_name="статус подписки",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="services.services",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на сервис",
                "verbose_name_plural": "Подписки на сервисы",
                "ordering": ("user",),
            },
        ),
    ]
