# Generated by Django 5.0.2 on 2024-03-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="icon",
        ),
        migrations.AddField(
            model_name="services",
            name="icon_big",
            field=models.ImageField(
                blank=True,
                default=None,
                upload_to="services/images/",
                verbose_name="Иконка сервиса большая",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="icon_small",
            field=models.ImageField(
                blank=True,
                default=None,
                upload_to="services/images/",
                verbose_name="Иконка сервиса маленькая",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="icon_square",
            field=models.ImageField(
                blank=True,
                default=None,
                upload_to="services/images/",
                verbose_name="Иконка сервиса квадратная",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="is_poplular",
            field=models.BooleanField(
                default=1, max_length=250, verbose_name="Популярность сервиса"
            ),
            preserve_default=False,
        ),
    ]
