# Generated by Django 5.0.2 on 2024-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
        migrations.AddField(
            model_name='services',
            name='icon_big',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='services/images/big/', verbose_name='Фото сервиса большое'),
        ),
        migrations.AddField(
            model_name='services',
            name='icon_small',
            field=models.ImageField(default=None, null=True, upload_to='services/images/small/', verbose_name='Фото сервиса'),
        ),
        migrations.AddField(
            model_name='services',
            name='icon_square',
            field=models.ImageField(default=None, null=True, upload_to='services/images/square/', verbose_name='Фото сервиса'),
        ),
        migrations.AddField(
            model_name='services',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный сервис?'),
        ),
    ]
