# Generated by Django 5.0.2 on 2024-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_remove_services_icon_services_icon_big_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="is_poplular",
            field=models.BooleanField(
                default=False, max_length=250, verbose_name="Популярность сервиса"
            ),
        ),
    ]
