# Generated by Django 5.0.2 on 2024-03-24 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_category_icon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
