# Generated by Django 5.0.2 on 2024-04-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_alter_tarifflist_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarifflist",
            name="services_duration",
            field=models.IntegerField(
                choices=[
                    ("1", "Один месяц"),
                    ("3", "Три месяца"),
                    ("6", "Шесть месяцев"),
                    ("12", "Один год"),
                ],
                default="1",
                verbose_name="длительность тарифа",
            ),
        ),
        migrations.AlterField(
            model_name="tarifflist",
            name="tariff_promo_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="промо стоимость тарифа"
            ),
        ),
    ]
