# Generated by Django 5.0.2 on 2024-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_delete_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
