# Generated by Django 5.0.2 on 2024-03-31 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_services_is_poplular"),
    ]

    operations = [
        migrations.RenameField(
            model_name="services",
            old_name="is_poplular",
            new_name="is_popular",
        ),
    ]
