# Generated by Django 5.0.2 on 2024-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_tarifflist_services_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarifflist",
            name="services_duration",
            field=models.CharField(
                choices=[
                    ("1", "Один месяц"),
                    ("3", "Три месяца"),
                    ("6", "Шесть месяцев"),
                    ("12", "Один год"),
                ],
                default="1",
                max_length=20,
                verbose_name="длительность тарифа",
            ),
        ),
    ]
