# Generated by Django 5.0.2 on 2024-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_alter_tarifflist_services_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.TextField(verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="services",
            name="icon_small",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="services/images/small/",
                verbose_name="Фото сервиса маленькое",
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="icon_square",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="services/images/square/",
                verbose_name="Фото сервиса среднее",
            ),
        ),
    ]
