# Generated by Django 5.0.2 on 2024-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_subscription_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("subscribed", "Подписан"), ("not_subscribed", "Не подписан")],
                default="subscribed",
                max_length=20,
                verbose_name="статус подписки",
            ),
        ),
    ]
