# Generated by Django 5.0.2 on 2024-03-28 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='services',
            name='services_duration',
        ),
        migrations.RemoveField(
            model_name='services',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, help_text='введите адрес ссылки', unique=True, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.CharField(default=1, max_length=250, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, default=None, upload_to='services/images/', verbose_name='Фото сервиса'),
        ),
        migrations.AddField(
            model_name='services',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=250, verbose_name='описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default=None, upload_to='category/images/', verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='название категории'),
        ),
        migrations.CreateModel(
            name='TariffList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название тарифа')),
                ('description', models.CharField(max_length=250, verbose_name='описание тарифа')),
                ('services_duration', models.CharField(choices=[('one_month', 'Один месяц'), ('three_months', 'Три месяца'), ('six_months', 'Шесть месяцев'), ('one_year', 'Один год')], default='one_month', max_length=20, verbose_name='длительность тарифа')),
                ('tariff_full_price', models.FloatField(verbose_name='полная стоимость тарифа')),
                ('tariff_promo_price', models.FloatField(verbose_name='промо стоимость тарифа')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifflists', to='services.services', verbose_name='сервис')),
            ],
        ),
    ]
