# Generated by Django 5.0.2 on 2024-03-28 20:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_services_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifflist',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
