# Generated by Django 5.0.2 on 2024-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_subscription_unique_user_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifflist',
            name='services_duration',
            field=models.CharField(choices=[('1', 'Один месяц'), ('3', 'Три месяца'), ('6', 'Шесть месяцев'), ('12', 'Один год')], default='1', max_length=20, verbose_name='длительность тарифа'),
        ),
    ]
