# Generated by Django 5.0.2 on 2024-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.TextField(
                        choices=[
                            (" SBP", "СБП"),
                            ("credit_card", "Кредитная карта"),
                            ("paypal", "PayPal"),
                            ("mobile_payment", "Мобильные платежи"),
                            ("cryptocurrency", "Платежные системы криптовалюты"),
                        ],
                        default=" SBP",
                        max_length=20,
                        verbose_name="Способ оплаты подписки",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default=None,
                        upload_to="payments/images/",
                        verbose_name="Фото cпособа оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метод оплаты подписки",
                "verbose_name_plural": "Методы оплаты подписок",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCashback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_cashback",
                    models.CharField(
                        choices=[
                            ("fixed_amount", "Фиксированная сумма"),
                            ("percentage", "Процент от суммы платежа"),
                        ],
                        default="fixed_amount",
                        max_length=155,
                        verbose_name="Тип кэшбека",
                    ),
                ),
                (
                    "amount_cashback",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Количество кэшбека по тарифу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кэшбек сервиса",
                "verbose_name_plural": "Кэшбеки сервисов",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Сумма оплаты подписки",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Даты оплаты подписки"
                    ),
                ),
                (
                    "expired_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата истечения подписки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("payment_completed", "Оплата прошла"),
                            ("not_paid", "Не оплачено"),
                        ],
                        default="not_paid",
                        max_length=30,
                        verbose_name="Статус оплаты подписки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка и оплата",
                "verbose_name_plural": "Подписки и оплаты",
            },
        ),
        migrations.CreateModel(
            name="UserCashback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Текст кэшбека"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Количество кэшбека",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cashback_completed", "Кешбэк получен"),
                            ("cashback_not_received", "Кешбэк не получен"),
                        ],
                        default="cashback_not_received",
                        max_length=100,
                        verbose_name="Статус получения кэшбека",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кэшбек пользователя",
                "verbose_name_plural": "Кэшбеки пользователей",
                "ordering": ["-id"],
            },
        ),
    ]
