# Generated by Django 5.0.2 on 2024-03-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cashback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type_cashback",
                    models.CharField(
                        choices=[
                            ("fixed_amount", "Фиксированная сумма"),
                            ("percentage", "Процент от суммы платежа"),
                        ],
                        default="fixed_amount",
                        max_length=155,
                        verbose_name="Тип кэшбека",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "subscription_service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.TextField(
                        choices=[
                            ("credit_card", "Кредитная карта"),
                            ("paypal", "PayPal"),
                            ("mobile_payment", "Мобильные платежи"),
                            ("cryptocurrency", "Платежные системы криптовалюты"),
                        ],
                        default="credit_card",
                        max_length=155,
                        verbose_name="Пользовательская роль юзера",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                ("status", models.CharField(max_length=155)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.subscription",
                    ),
                ),
            ],
        ),
    ]
