# Generated by Django 5.0.2 on 2024-03-29 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashback",
            name="payment",
        ),
        migrations.AddField(
            model_name="cashback",
            name="payment_methods",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.paymentmethods",
                verbose_name="Способ оплаты",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="payment_methods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_payments",
                to="payments.paymentmethods",
                verbose_name="Способ оплаты",
            ),
        ),
    ]
