# Generated by Django 5.0.2 on 2024-04-04 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethods",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="servicecashback",
            name="service_cashback",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.services",
                verbose_name="Кэшбек сервиса",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="payment_methods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_payments",
                to="payments.paymentmethods",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="services.subscription",
                verbose_name="Подписка",
            ),
        ),
        migrations.AddField(
            model_name="usercashback",
            name="subscription_payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.subscriptionpayment",
                verbose_name="Платеж подписки",
            ),
        ),
        migrations.AddField(
            model_name="usercashback",
            name="tariff_cashback",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.tarifflist",
                verbose_name="Тариф сервиса",
            ),
        ),
        migrations.AddField(
            model_name="usercashback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
