# Generated by Django 5.0.2 on 2024-04-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethods",
            name="icon",
            field=models.ImageField(
                blank=True,
                default=None,
                upload_to="payments/images/",
                verbose_name="Фото cпособа оплаты",
            ),
        ),
    ]
