# Generated by Django 5.0.2 on 2024-04-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="expired_date",
            field=models.DateField(verbose_name="Дата истечения подписки"),
        ),
    ]
