# Generated by Django 5.0.2 on 2024-03-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashback",
            options={
                "ordering": ["-id"],
                "verbose_name": "Кэшбек",
                "verbose_name_plural": "Кэшбеки",
            },
        ),
        migrations.AlterModelOptions(
            name="paymenthistory",
            options={
                "ordering": ["-id"],
                "verbose_name": "История оплаты подписки",
                "verbose_name_plural": "История оплат подписок",
            },
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_method",
            field=models.TextField(
                choices=[
                    ("credit_card", "Кредитная карта"),
                    ("paypal", "PayPal"),
                    ("mobile_payment", "Мобильные платежи"),
                    ("cryptocurrency", "Платежные системы криптовалюты"),
                ],
                default="credit_card",
                max_length=155,
                verbose_name="Способ оплаты подписки",
            ),
        ),
    ]
