# Generated by Django 5.0.2 on 2024-04-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_servicecashback_type_cashback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercashback",
            name="description",
            field=models.TextField(blank=True, verbose_name="Текст кэшбека"),
        ),
    ]
