# Generated by Django 5.0.2 on 2024-03-24 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0003_alter_cashback_options_alter_paymenthistory_options_and_more",
        ),
        ("services", "0003_delete_faq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashback",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Количество кэшбека"
            ),
        ),
        migrations.AlterField(
            model_name="cashback",
            name="description",
            field=models.TextField(verbose_name="Текст кэшбека"),
        ),
        migrations.AlterField(
            model_name="cashback",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.paymenthistory",
                verbose_name="История оплаты подписки",
            ),
        ),
        migrations.AlterField(
            model_name="cashback",
            name="status",
            field=models.CharField(max_length=100, verbose_name="Статус кэшбека"),
        ),
        migrations.AlterField(
            model_name="cashback",
            name="subscription_service",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.services",
                verbose_name="Сервис подписки",
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="services.subscription",
                verbose_name="Подписка",
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
