# Generated by Django 5.0.2 on 2024-04-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_alter_subscriptionpayment_expired_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecashback",
            name="type_cashback",
            field=models.CharField(
                choices=[
                    ("fixed_amount", "Фиксированная сумма"),
                    ("percentage", "Процент от суммы платежа"),
                ],
                default="percentage",
                max_length=155,
                verbose_name="Тип кэшбека",
            ),
        ),
    ]
