# Generated by Django 5.0.2 on 2024-03-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_alter_cashback_amount_alter_cashback_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_method",
            field=models.TextField(
                choices=[
                    (" SBP", "СБП"),
                    ("credit_card", "Кредитная карта"),
                    ("paypal", "PayPal"),
                    ("mobile_payment", "Мобильные платежи"),
                    ("cryptocurrency", "Платежные системы криптовалюты"),
                ],
                default="credit_card",
                max_length=155,
                verbose_name="Способ оплаты подписки",
            ),
        ),
    ]
