# Generated by Django 5.0.2 on 2024-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_alter_servicecashback_type_cashback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="expired_date",
            field=models.DateField(null=True, verbose_name="Дата истечения подписки"),
        ),
    ]
