# Generated by Django 5.0.2 on 2024-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_alter_paymenthistory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Способ оплаты подписки"
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_method",
            field=models.TextField(
                choices=[
                    (" SBP", "СБП"),
                    ("credit_card", "Кредитная карта"),
                    ("paypal", "PayPal"),
                    ("mobile_payment", "Мобильные платежи"),
                    ("cryptocurrency", "Платежные системы криптовалюты"),
                ],
                default="credit_card",
                max_length=20,
                verbose_name="Способ оплаты подписки",
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("payment_completed", "Оплата прошла"),
                    ("not_paid", "Не оплачено"),
                ],
                default="payment_completed",
                max_length=30,
                verbose_name="Статус оплаты подписки",
            ),
        ),
    ]
