# Generated by Django 5.0.2 on 2024-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_alter_paymenthistory_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashback",
            name="status",
            field=models.CharField(
                choices=[
                    ("cashback_completed", "Кешбэк получен"),
                    ("cashback_not_received", "Кешбэк не получен"),
                ],
                default="cashback_not_received",
                max_length=100,
                verbose_name="Статус получения кэшбека",
            ),
        ),
    ]
