# Generated by Django 5.0.2 on 2024-03-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_alter_cashback_status"),
        ("services", "0007_alter_subscription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_payments",
                        to="payments.paymenthistory",
                        verbose_name="История оплаты",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="services.subscription",
                        verbose_name="Подписка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка и оплата",
                "verbose_name_plural": "Подписки и оплаты",
            },
        ),
    ]
