# Generated by Django 5.0.2 on 2024-04-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_alter_paymentmethods_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethods",
            name="payment_method",
            field=models.TextField(
                choices=[
                    ("СБП", "Sbp"),
                    ("MasterCard **** 1324", "Credit Card"),
                    ("PayPal", "Paypal"),
                    ("Мобильные платежи", "Mobile Payment"),
                    ("Платежные системы криптовалюты", "Cryptocurrency"),
                ],
                default="СБП",
                verbose_name="Способ оплаты подписки",
            ),
        ),
    ]
