# Generated by Django 5.0.2 on 2024-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_question",
                    models.CharField(max_length=250, verbose_name="Тема вопроса"),
                ),
                (
                    "сategory",
                    models.CharField(
                        choices=[
                            ("registration", "Оформление"),
                            ("connection", "Подключение"),
                            ("work_with_subscriptions", "Работа с подписками"),
                        ],
                        max_length=25,
                        verbose_name="категория вопроса",
                    ),
                ),
                ("question", models.CharField(max_length=250, verbose_name="Вопрос")),
                ("answer", models.CharField(max_length=1000, verbose_name="Ответ")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания вопроса"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата обновления вопроса"
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQS",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="faqs_faq_created_4f1860_idx"
                    )
                ],
            },
        ),
    ]
