# Generated by Django 5.0.2 on 2024-03-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='сategory',
            field=models.CharField(choices=[('registration', 'Оформление'), ('connection', 'Подключение'), ('work_with_subscriptions', 'Работа с подписками')], default=1, max_length=25, verbose_name='категория вопроса'),
            preserve_default=False,
        ),
    ]
