# Generated by Django 5.0.2 on 2024-03-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="День Рождения пользователя"
            ),
        ),
    ]
